teams:
- name: karmada-adopter-group
  maintainers:
  - kevin-wangzefeng
  - RainbowMango
  members:
  - Allen-987 # SenseTime
  - baizhushui # SenseTime
  - CharlesQQ # HelloGroup
  - dongjiang1989 # iFLYTEK
  - gjbravi # Wellhub
  - guozheng-shen # Tongcheng Travel
  - ivan-cai # Alibaba Cloud
  - kechujian-creator # Songke
  - LivingCcj # Bilibili
  - liwang0513 # Bloomberg
  - NickYadance # Shopee
  - stulzq # Tongcheng Travel
  - vie-serendipity # Alibaba Cloud
  - xiaokangwang1992 # GMI Cloud
  - yangsoon # RedNote
  - zach593 # Trip.com Group
  - ZhengXinwei-F # SenseTime
- name: karmada-maintainers
  maintainers:
  - kevin-wangzefeng
  - RainbowMango
  members:
  - carmark
  - CharlesQQ
  - GitHubxsy
  - jabellard
  - lfbear
  - mrlihanbo
  - mszacillo
  - seanlaii
  - warjiang
  - wawa0210
  - whitewindmills
  - XiShanYongYe-Chang
  - zach593
  - zhzhuang-zju
  - zoroyouxi
- name: repo-admins
  maintainers:
  - kevin-wangzefeng
  - RainbowMango
  members:
  - karmada-bot
- name: karmada-security-team
  maintainers:
  - kevin-wangzefeng
  - RainbowMango
  members:
  - warjiang
  - yanfeng1992
  - zhzhuang-zju
repositories:
- name: api
  teams:
    repo-admins: admin
  visibility: public
- name: community
  teams:
    repo-admins: admin
  visibility: public
- name: dashboard
  teams:
    repo-admins: admin
  visibility: public
- name: karmada
  teams:
    repo-admins: admin
  visibility: public
- name: kubernetes
  teams:
    repo-admins: admin
  visibility: public
- name: multi-cluster-ingress-nginx
  teams:
    repo-admins: admin
  visibility: public
- name: multicluster-cloud-provider
  teams:
    repo-admins: admin
  visibility: public
- name: playground
  teams:
    repo-admins: admin
  visibility: public
- name: website
  teams:
    repo-admins: admin
  visibility: public
